services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./app/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fastapi:
    image: takyam15/fastapi-prod
    container_name: fastapi
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        REQ_DIR: "requirements/"
        REQ_TXT: "requirements/prod.txt"
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - postgres
  nginx:
    image: takyam15/fastapi-nginx-prod
    container_name: nginx
    build: ./nginx
    volumes:
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  postgres_data:
