from sqlalchemy import Column, Date, Integer, Numeric, SmallInteger, String, Table
from sqlalchemy.orm import mapped_column

from . import autogenerated_models


class CategoryModel(autogenerated_models.Category):
    category_small_cd = mapped_column(String(2), use_existing_column=True)
    category_major_cd = mapped_column(String(32), use_existing_column=True)
    category_major_name = mapped_column(String(4), use_existing_column=True)
    category_medium_cd = mapped_column(String(32), use_existing_column=True)
    category_medium_name = mapped_column(String(6), use_existing_column=True)
    category_small_name = mapped_column(String(32), use_existing_column=True)


t_geocode = Table(
    'geocode', autogenerated_models.metadata,
    Column('postal_cd', String(8)),
    Column('prefecture', String(4)),
    Column('city', String(30)),
    Column('town', String(30)),
    Column('street', String(30)),
    Column('address', String(30)),
    Column('full_address', String(80)),
    Column('longitude', Numeric),
    Column('latitude', Numeric),
    extend_existing=True
)


class StoreModel(autogenerated_models.Store):
    store_cd = mapped_column(String(6), use_existing_column=True)
    store_name = mapped_column(String(128), use_existing_column=True)
    prefecture_cd = mapped_column(String(2), use_existing_column=True)
    prefecture = mapped_column(String(5), use_existing_column=True)
    address = mapped_column(String(128), use_existing_column=True)
    address_kana = mapped_column(String(128), use_existing_column=True)
    tel_no = mapped_column(String(20), use_existing_column=True)
    longitude = mapped_column(Numeric, use_existing_column=True)
    latitude = mapped_column(Numeric, use_existing_column=True)
    floor_area = mapped_column(Numeric, use_existing_column=True)


class CustomerModel(autogenerated_models.Customer):
    customer_id = mapped_column(String(14), use_existing_column=True)
    customer_name = mapped_column(String(20), use_existing_column=True)
    gender_cd = mapped_column(String(1), use_existing_column=True)
    gender = mapped_column(String(2), use_existing_column=True)
    birth_day = mapped_column(Date, use_existing_column=True)
    age = mapped_column(Integer, use_existing_column=True)
    postal_cd = mapped_column(String(8), use_existing_column=True)
    address = mapped_column(String(128), use_existing_column=True)
    application_store_cd = mapped_column(String(6), use_existing_column=True)
    application_date = mapped_column(String(8), use_existing_column=True)
    status_cd = mapped_column(String(12), use_existing_column=True)


class ProductModel(autogenerated_models.Product):
    product_cd = mapped_column(String(10), use_existing_column=True)
    category_major_cd = mapped_column(String(2), use_existing_column=True)
    category_medium_cd = mapped_column(String(4), use_existing_column=True)
    category_small_cd = mapped_column(String(6), use_existing_column=True)
    unit_price = mapped_column(Integer, use_existing_column=True)
    unit_cost = mapped_column(Integer, use_existing_column=True)


class ReceiptModel(autogenerated_models.Receipt):
    sales_ymd = mapped_column(Integer, nullable=False, use_existing_column=True)
    store_cd = mapped_column(String(6), nullable=False, use_existing_column=True)
    receipt_no = mapped_column(SmallInteger, nullable=False, use_existing_column=True)
    receipt_sub_no = mapped_column(SmallInteger, nullable=False, use_existing_column=True)
    sales_epoch = mapped_column(Integer, use_existing_column=True)
    customer_id = mapped_column(String(14), use_existing_column=True)
    product_cd = mapped_column(String(10), use_existing_column=True)
    quantity = mapped_column(Integer, use_existing_column=True)
    amount = mapped_column(Integer, use_existing_column=True)
